# GitHub Actions workflow to build and push a Docker image
name: Build & Push Docker Image

on:
  # Trigger the workflow when pushing to main or any 'releases/*' branch
  push:
    branches:
      - master

  # Allow manual triggering from the GitHub UI
  workflow_dispatch:

jobs:
  build-and-push:
    # Run this job on the latest Ubuntu runner
    runs-on: ubuntu-latest

    # Grant permissions to access repo contents and push to GitHub Packages
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up QEMU to support building images for multiple architectures
      - name: Set up QEMU (for cross-platform builds)
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      # Step 3: Set up Docker Buildx, which supports advanced builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      # Step 4: Log in to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_GITHUBACTIONS_SECRET }}  # Set this in repo secrets


      # Step 6: Build and push the Docker image
      - name: Build & push image
        uses: docker/build-push-action@v4
        with:
          context: .                # Use current directory as Docker build context
          file: ./Dockerfile        # Path to Dockerfile
          platforms: linux/amd64,linux/arm64  # Build for both major architectures
          push: true                # Push the image to the registry
          tags: |                   # Define image tags for GHCR and Docker Hub
            ghcr.io/${{ github.repository }}/aetheris-one:latest
            ghcr.io/${{ github.repository }}/aetheris-one:${{ github.sha }}
            docker.io/${{ secrets.DOCKERHUB_USERNAME }}/aetheris-one:latest